import './styles.css'; import {supabase,configured} from './supabase'
const app=document.querySelector('#app');let session,household,profile,active='bridge',channel
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))
const nav=()=>`<nav class="nav">${['bridge','agenda','crew','log','more'].map(x=>`<button data-tab="${x}" class="${active===x?'active':''}">${x.toUpperCase()}</button>`).join('')}</nav>`
const top=t=>`<header class="top"><div><div class="brand">${E(t||'The Bridge')}</div><div class="muted">${E(household?.name||'')}</div></div><button id="logout" class="ghost">Log out</button></header>`
function wire(){logout?.addEventListener('click',()=>supabase.auth.signOut());document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;render()})}
async function userData(){let u=session.user.id;profile=(await supabase.from('profiles').select('*').eq('user_id',u).maybeSingle()).data;let m=(await supabase.from('household_members').select('household_id').eq('user_id',u).limit(1).maybeSingle()).data;household=m?(await supabase.from('households').select('*').eq('id',m.household_id).single()).data:null}
function auth(){app.innerHTML=`<main class="shell"><section class="panel auth"><div class="brand">The Bridge</div><h1>Permission to come aboard?</h1><div class="tabs"><button id="li" class="active">Log in</button><button id="su">Sign up</button></div><form id="af"><div class="field"><label>Email</label><input id="em" type="email" required></div><div class="field"><label>Password</label><input id="pw" type="password" minlength="6" required></div><button class="primary">ENTER THE BRIDGE</button><p id="err" class="error"></p></form></section></main>`;let mode='login';li.onclick=()=>{mode='login';li.className='active';su.className=''};su.onclick=()=>{mode='signup';su.className='active';li.className=''};af.onsubmit=async e=>{e.preventDefault();let r=mode==='signup'?await supabase.auth.signUp({email:em.value,password:pw.value}):await supabase.auth.signInWithPassword({email:em.value,password:pw.value});if(r.error)err.textContent=r.error.message}}
function onboard(){app.innerHTML=`<main class="shell"><section class="panel setup"><div class="brand">Crew Registration</div>${!profile?`<h1>Create your profile</h1><form id="pf"><div class="field"><label>Name</label><input id="dn" required></div><div class="field"><label>Nickname</label><input id="nn"></div><button class="primary">SAVE PROFILE</button></form>`:`<h1>Join your ship</h1><div class="tabs"><button id="create" class="primary">Create household</button><button id="join">Join with code</button></div><div id="ja"></div>`}<p id="msg" class="error"></p></section></main>`;if(!profile)pf.onsubmit=async e=>{e.preventDefault();let r=await supabase.from('profiles').insert({user_id:session.user.id,display_name:dn.value,nickname:nn.value});if(r.error)return msg.textContent=r.error.message;await userData();onboard()};else{create.onclick=async()=>{let r=await supabase.rpc('create_household',{household_name:'The Bridge'});if(r.error)return msg.textContent=r.error.message;await userData();await seed();sub();active='crew';render()};join.onclick=()=>{ja.innerHTML=`<form id="jf"><div class="field"><label>Invite code</label><input id="ic" required></div><button class="primary">COME ABOARD</button></form>`;jf.onsubmit=async e=>{e.preventDefault();let r=await supabase.rpc('join_household',{code:ic.value});if(r.error)return msg.textContent=r.error.message;await userData();sub();active='crew';render()}}}}
async function seed(){let old=(await supabase.from('cats').select('id').eq('household_id',household.id).limit(1)).data;if(old?.length)return;let cats=(await supabase.from('cats').insert([{household_id:household.id,name:'Pukha',breed:'British Longhair',job_title:'Senior Household Supervisor'},{household_id:household.id,name:'Pluto',breed:'Domestic shorthair',job_title:'Head of Ruling From High Places'}]).select()).data;for(let c of cats||[])await supabase.from('cat_feeding_schedules').insert(['05:00','13:00','21:00'].map(t=>({cat_id:c.id,feeding_time:t})))}
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Dublin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function minsNow(){let p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()).split(':');return +p[0]*60 + +p[1]}
function tmins(t){let [h,m]=t.split(':');return +h*60 + +m}
async function bridge(){app.innerHTML=`<main class="shell">${top()}<div id="hunger"></div><div class="grid"><section class="panel hero"><span class="muted">CURRENTLY ABOARD:</span><h1>${E(profile?.display_name)}</h1><div>Why don't starships ever get lost?<br><span class="muted">They always follow their enterprise.</span></div></section><section class="panel card cats"><div class="section-title">The children</div><div id="cats" class="catrow">Scanning…</div></section><section class="panel card notes"><div class="section-title">Sticky notes</div><div class="sticky">There is cake in the fridge.<br><br>This is not a drill.</div></section><section class="panel card agenda"><div class="section-title">Today</div><div class="row"><span>TAKE YOUR DRUGS</span><span>!</span></div></section><section class="panel card ops"><div class="section-title">House status</div><div class="muted">No disasters currently detected. Suspicious.</div></section></div></main><button id="plus" class="plus">+</button><section id="menu" class="panel menu" hidden><button>NOTE</button><button>TASK</button><button>PLAN</button><button>STUFF</button><button>MONEY</button></section>${nav()}`;wire();plus.onclick=()=>menu.hidden=!menu.hidden;await cats()}
async function cats(){let cs=(await supabase.from('cats').select('*,cat_feeding_schedules(*)').eq('household_id',household.id).order('name')).data||[];let fs=(await supabase.from('cat_feedings').select('*').eq('household_id',household.id).eq('feeding_date',localDate()).order('recorded_at',{ascending:false})).data||[];let users=[...new Set(fs.map(x=>x.recorded_by))],names={};if(users.length){for(let p of (await supabase.from('profiles').select('user_id,display_name').in('user_id',users)).data||[])names[p.user_id]=p.display_name}
let overdue=false;cats.innerHTML=cs.map(c=>{let schedules=(c.cat_feeding_schedules||[]).sort((a,b)=>a.feeding_time.localeCompare(b.feeding_time));return `<article class="cat"><div class="catname">${E(c.name)}</div><div class="muted">${E(c.breed)}</div><div class="bowls">${schedules.map(s=>{let f=fs.find(x=>x.cat_id===c.id&&x.schedule_id===s.id),late=!f&&minsNow()>tmins(s.feeding_time)+60;if(late)overdue=true;let cl=f?f.status:late?'overdue':'',txt=f?f.status.toUpperCase():late?'HUNGRY':'○',stamp=f?`<div class="stamp">${E(names[f.recorded_by]||'Crew')} · ${new Date(f.recorded_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div>`:'';return `<button class="bowl ${cl}" data-cat="${c.id}" data-sch="${s.id}" data-time="${s.feeding_time.slice(0,5)}">${s.feeding_time.slice(0,5)}<br>${txt}${stamp}</button>`}).join('')}</div></article>`}).join('');hunger.innerHTML=overdue?`<div class="alert">THE CHILDREN HUNGER. THIS IS NOT A DRILL.</div>`:'';document.querySelectorAll('.bowl').forEach(b=>b.onclick=()=>feedModal(b.dataset.cat,b.dataset.sch,b.dataset.time))}
function feedModal(cat,sch,time){let wrap=document.createElement('div');wrap.className='modalWrap';wrap.innerHTML=`<section class="panel modal"><div class="section-title">Feeding report · ${E(time)}</div><p>What happened?</p><div class="statusBtns"><button data-s="fed">FED</button><button data-s="partial">PARTIAL</button><button data-s="refused">REFUSED</button><button data-s="other">OTHER</button></div><div class="field"><label>Optional note</label><textarea id="fn"></textarea></div><button id="cancel" class="ghost">Cancel</button><p id="fe" class="error"></p></section>`;document.body.appendChild(wrap);cancel.onclick=()=>wrap.remove();wrap.querySelectorAll('[data-s]').forEach(b=>b.onclick=async()=>{let r=await supabase.from('cat_feedings').insert({household_id:household.id,cat_id:cat,schedule_id:sch,feeding_date:localDate(),status:b.dataset.s,note:fn.value||null,recorded_by:session.user.id});if(r.error)return fe.textContent=r.error.message;wrap.remove();cats()})}
async function crew(){app.innerHTML=`<main class="shell">${top('Crew')}<section class="panel invite"><div class="section-title">Household invite code</div><div class="code">${E(household.invite_code)}</div></section><h1 class="pageTitle">Crew Manifest</h1><div id="cg" class="crewgrid"></div></main>${nav()}`;wire();let ms=(await supabase.from('household_members').select('user_id').eq('household_id',household.id)).data||[],ids=ms.map(x=>x.user_id),ps=ids.length?(await supabase.from('profiles').select('*').in('user_id',ids)).data||[]:[],cs=(await supabase.from('cats').select('*').eq('household_id',household.id)).data||[];cg.innerHTML=[...ps.map(p=>`<article class="panel crewcard"><div class="crewhead"><div class="avatar">${E((p.display_name||'?')[0])}</div><div><div class="crewname">${E(p.display_name)}</div><div class="muted">${E(p.nickname||'Human')}</div></div></div></article>`),...cs.map(c=>`<article class="panel crewcard"><div class="crewname">${E(c.name)}</div><div class="muted">${E(c.breed)}</div></article>`)].join('')}
function placeholder(t){app.innerHTML=`<main class="shell">${top(t)}<section class="panel card"><h1 class="pageTitle">${E(t)}</h1><p class="muted">Coming soon.</p></section></main>${nav()}`;wire()}
function render(){if(active==='bridge')bridge();else if(active==='crew')crew();else placeholder(active==='log'?"Captain's Log":active[0].toUpperCase()+active.slice(1))}
function sub(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('bridge-live-'+household.id).on('postgres_changes',{event:'*',schema:'public',table:'cat_feedings',filter:`household_id=eq.${household.id}`},()=>{if(active==='bridge')cats()}).on('postgres_changes',{event:'*',schema:'public',table:'household_members',filter:`household_id=eq.${household.id}`},()=>{if(active==='crew')crew()}).subscribe()}
async function boot(){if(!configured)return auth();session=(await supabase.auth.getSession()).data.session;if(session){await userData();household?(sub(),render()):onboard()}else auth();supabase.auth.onAuthStateChange(async(_,s)=>{session=s;if(!s){profile=household=null;return auth()}await userData();household?(sub(),render()):onboard()})}boot()
